---
title: "Main.Rmd"
author: Blezz (BlezzRot, Blezz-Tech)
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: true
    theme: default
    code_folding: show
  pdf_document:
    latex_engine: xelatex
---

# Main

```{r}

2 + 1

sin(pi/6)

cats <- 5
dogs <- 2
pets <- cats + dogs

ls()

# ?rnorm

rnorm(15, mean = 5, sd = 3)

returntwo <- function() {
  y <- 2
  return(y)
}

returntwo()


addten <- function(x) { 
  x <- x + 10
}

addten(cats)
cats


addten <- function(x) { 
  return(x + 10)
}

morecats <- addten(cats)
morecats


addten <- function(x) { 
  moredogs <<- x + 10
}

addten(dogs)
dogs
moredogs

ls()

rm(dogs)
rm(moredogs)
ls() 

# Удаление всех переменных. Аккуратно
rm(list = ls())
ls()



# ?help
# ?help.search

# ?`<-`
# ?ls

# ?`function`
# ?rm

x <- vector(length = 2)
x[1] <- 5
x[2] <- 8
x

y <- c(x, 1, c(3, 4), x, NA)
y

c(x, y)

5:9
3:-1

seq(1, 2, by = 0.25)

seq(3, 4, length.out = 5)

seq(3, 4, length = 5)

seq(3, 4, length = 11)

rep(1:3, times = 3)

rep(1:3, each = 4)

rep(1:3, length.out = 5)
```


# Plots

```{r}
library(ggplot2)
# library(svglite)

# svglite("myplot.svg", width = 200, height = 200)

eq = function(x){x^3 - 5*x}
ggplot(data.frame(x=c(-4, 4)), aes(x=x)) + 
  stat_function(fun=eq)

# dev.off()
# ggsave("build/myplot.svg", width = 2000, height = 2000, units = "px")

```














